name: Workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    name: Job
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Change number
        run: echo $RANDOM > file.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'commit message'
          default_author: github_actions
          committer_name: GitHub Actions
          committer_email: actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
